In [1]:
import torch


In [7]:
a = torch.arange(1, 10)

a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
torch.cumprod(a, -1)

tensor([     1,      2,      6,     24,    120,    720,   5040,  40320, 362880])

In [3]:
b = torch.tensor([3, 1, 5])

In [7]:
a[b]

tensor([3, 1, 5])

In [8]:
a[b].view(-1, 1, 1, 1)

tensor([[[[3]]],


        [[[1]]],


        [[[5]]]])

In [10]:
t = torch.randint(0, 10-1, (3, ))

t

tensor([5, 7, 6])